### ISSUE TITLE
一个命名的小建议

### ISSUE THREAD

**Issue by anqur** [zoom-quiet/scm#1]
- 啊, 简单的看了下里面的文件, 发现好像 repo 名叫 `dotfiles` 或 `scripts` 合适一些?...
  + `dotfiles` 的话就是一些以点为前缀的配置文件的备份
  + `scripts` 就是一些实用脚本
- 在 GitHub 上搜这些关键字的话也比较好查到别人的相关配置唔

**Comment by ZoomQuiet** [comment]
@anqurvanillapy 是也乎,(￣▽￣)

- 多谢, 只是, 并不都是 dotfile, 
- 又不想分仓库, 所以使用了以往的习惯命名
- 毕竟是私人配置, 也没什么技巧可言

多谢关注 ;-)
